CREATE DATABASE `dev_vote` DEFAULT CHARACTER SET `utf8`;
CREATE USER 'samurai'@'localhost' IDENTIFIED BY 'samurai';
REVOKE CREATE ROUTINE, CREATE VIEW, CREATE USER, ALTER, SHOW VIEW, CREATE, ALTER ROUTINE, EVENT, SUPER, INSERT, RELOAD, SELECT, DELETE, FILE, SHOW DATABASES, TRIGGER, SHUTDOWN, REPLICATION CLIENT, GRANT OPTION, PROCESS, REFERENCES, UPDATE, DROP, REPLICATION SLAVE, EXECUTE, LOCK TABLES, CREATE TEMPORARY TABLES, INDEX ON *.* FROM 'samurai'@'localhost';
GRANT CREATE ROUTINE, CREATE VIEW, ALTER, SHOW VIEW, CREATE, ALTER ROUTINE, EVENT, INSERT, SELECT, DELETE, TRIGGER, GRANT OPTION, REFERENCES, UPDATE, DROP, EXECUTE, LOCK TABLES, CREATE TEMPORARY TABLES, INDEX ON `dev\_vote`.* TO 'samurai'@'localhost';
FLUSH PRIVILEGES;



CREATE TABLE `vote` (
  `pk` bigint(11) unsigned NOT NULL AUTO_INCREMENT,
  `questionId` int(11) NOT NULL DEFAULT '0',
  `userName` varchar(1024) NOT NULL DEFAULT '',
  `area` varchar(128) NOT NULL DEFAULT '',
  `price` varchar(512) NOT NULL DEFAULT '',
  `createDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

